//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comma.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noun
    {
        public string Noun1 { get; set; }
        public int NounID { get; set; }
        public Nullable<int> DefinitionID { get; set; }
    
        public virtual NounsDefinition NounsDefinition { get; set; }
    }
}
