//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comma.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimpuriVerbale
    {
        public int ID { get; set; }
        public Nullable<int> TimpID { get; set; }
        public string Eu { get; set; }
        public string Tu { get; set; }
        public string Ea { get; set; }
        public string Noi { get; set; }
        public string Voi { get; set; }
        public string Ele { get; set; }
        public Nullable<int> VerbID { get; set; }
    
        public virtual Verb Verb { get; set; }
    }
}
