//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comma.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verb()
        {
            this.TimpuriVerbales = new HashSet<TimpuriVerbale>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OriginalID { get; set; }
        public string RawVerb { get; set; }
        public string OriginalVerb { get; set; }
        public Nullable<int> DefinitionID { get; set; }
        public string Infinitiv { get; set; }
        public string InfinitivLung { get; set; }
        public string Gerunziu { get; set; }
        public string Participiu { get; set; }
        public string ImperativSingular { get; set; }
        public string ImperativPlural { get; set; }
        public Nullable<bool> AreTimpuri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimpuriVerbale> TimpuriVerbales { get; set; }
    }
}
