//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comma.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Under33_ProdEntities : DbContext
    {
        public Under33_ProdEntities()
            : base("name=Under33_ProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Noun> Nouns { get; set; }
        public virtual DbSet<NounsDefinition> NounsDefinitions { get; set; }
        public virtual DbSet<Verb> Verbs { get; set; }
    }
}
